### PR TITLE
Private properties

### PR DESCRIPTION
**Pull request by kordan**

### CODE REVIEW

**Comment by kordan** [comment]
1 -----------------------
cover=0 as param in the URL of view.php left. It was 100% useless, but I needed many months to get it. Sorry! I am not higher than me.

2 -----------------------
Landing pages have now a speaking name. Names are now: <<tabs>>_<<page>>.php like, for instance: view_search.php explaining that that file manages the page that comes out by selecting the "Layout" tab and choosing the "Search" page.
Landing pages of the "Survey" tab are named: view_*.php.
The same is true for the landing pages of master and usr templates.
Corresponding class has been renamed with a name more similar to the calling page.

3 -----------------------
An awful error has been fixed. The story is here. Let's talk about a multipage surveypro. I am in page k. There I provide the answer to few items and I push the "<< back" button to return to page k-1. At submission time, surveypro code ALWAYS saves the answer for each item. THIS IS TRUE EVEN IF THE PAGE WAS NOT 100% ANSWERED. This was requested by user a long time ago and now it is months that the module has this exciting feature. The problem I just fixed was with the date* (date, datetime, shordate...) items. When they were still set to "Choose..." the save process was rising up an issue. It has now been fixed.

4 -----------------------
$this->canxxx no longer exists. Capability are saved to local variables and recalculated at the beginning of each method.

5 -----------------------
view_preview has been created and has now the same dignity of the other landing pages.

6 -----------------------
Following the idea to reduce the visibility of methods and properties, I changed a bit the code of the landing pages in order to reduce the number of public properties.

7 -----------------------
bloody news: I see tabs.class.php in this branch. I am 100% sure it comes from my mistake. I apologise.

8 -----------------------
Two errors were fixed in the usertemplates available in test/fixtures/usertemplates folder.
The story is here even if it is quite long. I divided it into four steps.
1) For "Select", "Radio button" and "Checkbox" items the ET (editing teacher or whoever in charge of the creation of a surveypro) can create elements where value and label are different.
((1a) It is simple: In the "Options" field of the "select" item creation write

IT::Italy
ES::Spain
FR::France
CH::Switzerland
DE::Germany

instead of (1b)

Italy
Spain
France
Switzerland
Germany
)
In detail: he can create a select like the following one:
<select bla bla bla>
 <option value="IT">Italy</option>
 <option value="ES">Spain</option>
 <option value="FR">France</option>
 <option value="CH">Switzerland</option>
 <option value="DE">Germany</option>
</select>
where the <<label>> "Spain" is different from the <<<value>> "ES" that will be saved to the database.
Good.

2) For that items the ET can even choose a default. The vexed (it was the reason of some centuries of meetings) issue is: When the ET chooses a default what has to specify? The <<value>> or the <<label>>? I other words: if I want my html "select" default to Spain, what am I supposed to write in the "default" field during item creation? "ES" or "Spain"? I was an herald of VALUE VALUE VALUE!! But at the end they won against me because...

3) because the ET can also use the "Other" field by defining the label of the "other" option of the select. That option will be bound to an input field like:
<input name="<<itemid>>_text" />
So if the ET sets:
"Other option" to "Other (please specify)"
the html code of the select in the form will change to 
<select bla bla bla>
 <option value="IT">Italy</option>
 <option value="ES">Spain</option>
 <option value="FR">France</option>
 <option value="CH">Switzerland</option>
 <option value="DE">Germany</option>
 <option value="<<itemid>>_other">Other (please specify)</option>
</select>
<input name="<<itemid>>_text" />

If the user chooses "Other (please specify)" he will be forced to enter a value in the <input name="<<itemid>>_text" /> and in the database will be saved the content of that field.

4) The ET is further allowed to choose a default for that "other_text" field.
So by setting "Other option" to "Other (please specify)->myDefault"
the form html will change to
<select bla bla bla>
 <option value="IT">Italy</option>
 <option value="ES">Spain</option>
 <option value="FR">France</option>
 <option value="CH">Switzerland</option>
 <option value="DE">Germany</option>
 <option value="<<itemid>>_other">Other (please specify)</option>
</select>
<input name="<<itemid>>_text" value="myDefault" />

Well, the overall idea of this long story is that
a) the ET will ALWAYS write labels for each element of the "select"
b) it is NOT true he will ALWAYS write each value like explained in 3) where the content of the input text field is null.

Because of this I changed, some months ago, the management of the default. It is no longer expecting VALUES but LABELS.

The issue I fixed is this: in the usertemplates provided in test/fixtures/usertemplates the defaultvalue provided was still a VALUE and not a LABEL.

**Comment by stronk7** [comment]
Before merging this... from the 9 commits above... which ones are really the desired ones? Only 7e80393 (the WIP one) ?

If you confirm me that only such commit is the needed one for this PR, I'd suggest you to commit --amend it in order to get rid of the "WIP" word in the commit message. Usually that word is used when something is not finished and you've had to save stuff in an "interim" commit (like we did yesterday). If now the commit is ready and finished... it should not contain such a word. It's a general "etiquette" thing.

Also, I can look to #22 but I need confirmation about when I should look to those commits here or in the original PR, because right now it's conflicting there. Please tell me if it's ok to look to everything here (both the tabs stuff and the private thing). And I will, ignoring #22.

Ciao :-)

**Comment by kordan** [comment]
I tried to follow your suggestions but with few difficulties.
I started with 
git commit --amend
I changed the first line of the message and I
git push origin private_properties

but this was not successfull
the story continued as in the following description.

[daniele@/Applications/MAMP/htdocs/head/mod/surveypro (private_properties $)]$ git push origin private_properties
To git@github.com:kordan/moodle-mod_surveypro.git
 ! [rejected]        private_properties -> private_properties (non-fast-forward)
error: failed to push some refs to 'git@github.com:kordan/moodle-mod_surveypro.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Merge the remote changes (e.g. 'git pull')
hint: before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

[daniele@/Applications/MAMP/htdocs/head/mod/surveypro (private_properties $)]$ git pull origin private_properties 
From github.com:kordan/moodle-mod_surveypro
 * branch            private_properties -> FETCH_HEAD
Auto-merging field/numeric/classes/plugin.class.php
CONFLICT (content): Merge conflict in field/numeric/classes/plugin.class.php
Automatic merge failed; fix conflicts and then commit the result.

[daniele@/Applications/MAMP/htdocs/head/mod/surveypro (private_properties *+$|MERGING)]$ git add .

[daniele@/Applications/MAMP/htdocs/head/mod/surveypro (private_properties +$|MERGING)]$ git commit --amend
fatal: You are in the middle of a merge -- cannot amend.

[daniele@/Applications/MAMP/htdocs/head/mod/surveypro (private_properties +$|MERGING)]$ git commit -m 'NOBUG mod_surveypro: merging because push was rejected'
[private_properties 7534136] NOBUG mod_surveypro: merging because push was rejected
[daniele@/Applications/MAMP/htdocs/head/mod/surveypro (private_properties $)]$ git push origin private_properties
Counting objects: 26, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (10/10), done.
Writing objects: 100% (12/12), 5.18 KiB, done.
Total 12 (delta 8), reused 0 (delta 0)
To git@github.com:kordan/moodle-mod_surveypro.git
   7e80393..7534136  private_properties -> private_properties

[daniele@/Applications/MAMP/htdocs/head/mod/surveypro (private_properties $)]$ git log --oneline
7534136 NOBUG mod_surveypro: merging because push was rejected
041b980 NOBUG mod_surveypro: private_properties
7e80393 NOBUG mod_surveypro: private_properties WIP
...

**Comment by kordan** [comment]
I tested each commit of this PR.
Really #22 (NOBUG_tabsupgrade2) seems useless now.

**Comment by kordan** [comment]
It seems that
git rebase -i master
git push origin private_properties --force
were fine here.
I leave you the floor.

**Comment by stronk7** [comment]
Side comment: You should verify the permissions in the files you create. They should not have the executable bit set. Don't worry, I'll create PR to fix all them, just saw a number of new files coming with this PR and having incorrect (execute) permissions. No action in needed your side.

**Comment by stronk7** [comment]
I'm getting these 2 errors with tests:

http://pastebin.com/9kPks5Uu

**Comment by kordan** [comment]
About your first error, it seems that you don't "see" the public function surveypro_has_the_following_items($surveyproname, TableNode $data)  that I have in 
https://github.com/kordan/moodle-mod_surveypro/blob/master/tests/behat/behat_mod_surveypro.php#L83
Here it runs fine.
MacBookProKordan:head kordan$ vendor/bin/behat --config /Applications/MAMP/data/behatdatahead/behat/behat.yml --name='Backup and restore a surveypro with some item'
Moodle 3.1dev (Build: 20160114), mysqli
Server OS "Darwin", Browser: "firefox"
Behat specific fixes have been applied. See http://docs.moodle.org/dev/Acceptance_testing#Browser_specific_fixes
Started at 19-02-2016, 02:06
.................................

1 scenario (1 passato)
33 step (33 passato)
2m33.949s

About your send error, this is what happened to me.
I ran the test and I got an error. Just after I ran again the same test and it worked fine!!!!

MacBookProKordan:head kordan$ vendor/bin/behat --config /Applications/MAMP/data/behatdatahead/behat/behat.yml --name='display each mastertemplate in 2 different languages'
Moodle 3.1dev (Build: 20160114), mysqli
Server OS "Darwin", Browser: "firefox"
Behat specific fixes have been applied. See http://docs.moodle.org/dev/Acceptance_testing#Browser_specific_fixes
Started at 19-02-2016, 01:54
........F-----------------------------------------------------------

(::) step falliti (::)

01. Sub-navigation node "Language" not found under "Site administration"
    In step `And I navigate to "Language packs" node in "Site administration > Language"'. # behat_navigation::i_navigate_to_node_in()
    From scenario `display each mastertemplate in 2 different languages'.                  # /Applications/MAMP/htdocs/head/mod/surveypro/tests/behat/multilang_mastertemplate.feature:28
    Of feature `verify multilang in ATTLS (20 item version) mastertemplate'.               # /Applications/MAMP/htdocs/head/mod/surveypro/tests/behat/multilang_mastertemplate.feature

1 scenario (1 fallito)
68 step (8 passato, 59 saltato, 1 fallito)
1m52.308s
MacBookProKordan:head kordan$ vendor/bin/behat --config /Applications/MAMP/data/behatdatahead/behat/behat.yml --name='display each mastertemplate in 2 different languages'
Moodle 3.1dev (Build: 20160114), mysqli
Server OS "Darwin", Browser: "firefox"
Behat specific fixes have been applied. See http://docs.moodle.org/dev/Acceptance_testing#Browser_specific_fixes
Started at 19-02-2016, 01:56
...................................................................... 70
.

1 scenario (1 passato)
71 step (71 passato)
5m44.171s

Mysteries of acceptance test!

**Comment by stronk7** [comment]
Ok, I'm merging this. Later can look to the failures in detail.

**Pull request merged**
