### PR TITLE
NOBUG mod_surveypro: added extra checks to surveypro_get_item

### PR DESCRIPTION
**Pull request by kordan**
According to our discussion I added the check of correctness of $type and $plugin in the frame of the surveypro_get_item function

### CODE REVIEW

**Comment by kordan** [comment]
Is there any problem with this PR? I already have one more very silly modification ready to push.
Any news about the weird failing duplicate.feature behat test?

**Comment by stronk7** [comment]
Merged, thanks!

Sorry Daniele, for some reason I had not received any notification about the new commits adding the cm check and so on. Just received your comment. Maybe that's the normal behavior, so whenever there are new commits to look, plz comment (here better as far as it will lead to mail notification).

About the failing feature... just pulling and testing now... will comment if I find anything...ciao :-)

**Comment by stronk7** [comment]
oh, oh. grrrr. i had the feeling something was wrong with that "itemseed" in your code... and was near to suggest to move the get_record() out from the "ifs", finally did not to avoid one more change here.

But I should because now, lots of tests are failing because "itemseed" is not defined always. So you should perform the "cm" verification only if there is a valid "itemseed". Without that extra condition, behat tests are failing here and there.

**Comment by stronk7** [comment]
Oh, really was unable to see anything. All scenarios but 1 failed:

39 escenarios (1 exitosos, 38 fallidos) :-(

**Comment by stronk7** [comment]
So we need one more commit checking if that "itemseed" exists or no before using it for the "cm" verification.

**Pull request merged**
