### PR TITLE
NOBUG mod_surveypro: unistalled old plugin

### PR DESCRIPTION
**Pull request by kordan**
I changed the name of the attachment_overview report to attachment
Now I have to uninstall the old report as it is declared "missing from the disk" in the moodle notification page.

### CODE REVIEW

**Comment by stronk7** [comment]
Ah, yes! I remember I saw the name change when reviewing the autoload? issue! But at the end forgot to comment about it with all the name changes and so on. Well spotted! The report subplugin is tableless, correct? I mean, t does not have any database structure.

**Comment by kordan** [comment]
yes, it is tableless

**Comment by stronk7** [comment]
thanks, merged!

**Comment by kordan** [comment]
Thanksssssss!

**Pull request merged**
