### PR TITLE
CONTRIB-6002 mod_surveypro: changed settings.php and bumped version n…

### PR DESCRIPTION
**Pull request by kordan**
CONTRIB-6002 mod_surveypro: changed settings.php and bumped version number to today

### CODE REVIEW

**Comment by kordan** [comment]
This my proposal to fix the issue CONTRIB-6002
See: https://tracker.moodle.org/browse/CONTRIB-6002

**Comment by kordan** [comment]
ok, I think the just submitted new version of the patch is complaint with your request

**Comment by stronk7** [comment]
Think that still you need to review the uses of those variables in the module. Because for sure you've calls to get_config() using the old "surveypro" instead of "mod_surveypro".

**Comment by kordan** [comment]
Strongly correct. This fix as it is now, opens a huge hole in the overall functionality of the module. Going to fix it. Thanks

**Comment by kordan** [comment]
ok. The tour start to be clearer. I fixed the calls to get_config as from your suggestion. Thanks.
I did not do any test.

**Comment by stronk7** [comment]
It looks great, I'm going to create a tiny phpunit test (our first one!). To verify that config defaults on new installed site are working as expected. Trivial test but useful as basic example. Will create issue about it.

**Comment by stronk7** [comment]
One more little comment/trick: as far as "mod_surveypro" is long, it's also perfectly valid to use "surveypro". Note that 2 of your commits exceed the recommended 72 characters long max. No problem at this stage, but incorrect for the future.

**Comment by stronk7** [comment]
Merged, many thanks!

**Pull request merged**
