### PR TITLE
Reduced the validity of the field trimonsave

### PR DESCRIPTION
**Pull request by kordan**
Each item (item = fields + formats) in surveypro uses a set of fields.
Some of them are (MORE OR LESS) common for each item, some of them are very specific for an item.
For instance: Content is a common field for EACH item. Signed is specific for numeric field ONLY.

The situation at the moment is described in the following table.

```
                   AGE |   AUTOFILL  | BOOLEAN | CHARACTER | CHECKBOX        | DATE | DATETIME | FILEUPLOAD | INTEGER | MULTISELECT     | NUMERIC  | RADIOBUTTON | RATE           | RECURRENCE | SELECT     | SHORTDATE | TEXTAREA  | TIME |    | FIELDSET      | FIELDSETEND | LABEL     | PAGEBREAK |
content          | √   |   √         | √       | √         | √               | √    | √        | √          | √       | √               | √        | √           | √              | √          | √          | √         | √         | √    | 18 | √             | NO          | √         | NO        |
contentformat    | √   |   √         | √       | √         | √               | √    | √        | √          | √       | √               | √        | √           | √              | √          | √          | √         | √         | √    | 18 | NO            | NO          | √         | NO        |

required         | √   |   NO        | √       | √         | √               | √    | √        | √          | √       | √               | √        | √           | √              | √          | √          | √         | √         | √    | 17 | NO            | NO          | NO        | NO        |
indent           | √   |   √         | √       | √         | √               | √    | √        | √          | √       | √               | √        | √           | √              | √          | √          | √         | √         | √    | 18 | NO            | NO          | √         | NO        |
position         | √   |   √         | √       | √         | √               | √    | √        | √          | √       | √               | √        | √           | √              | √          | √          | √         | √         | √    | 18 | NO            | NO          | NO        | NO        |
customnumber     | √   |   √         | √       | √         | √               | √    | √        | √          | √       | √               | √        | √           | √              | √          | √          | √         | √         | √    | 18 | NO            | NO          | √         | NO        |
hideinstructions | √   |   NO        | NO      | √         | √               | √    | √        | NO         | √       | √               | √        | NO          | √              | √          | NO         | √         | √         | √    | 13 | NO            | NO          | NO        | NO        |
variable         | √   |   √         | √       | √         | √               | √    | √        | √          | √       | √               | √        | √           | √              | √          | √          | √         | √         | √    | 18 | NO            | NO          | NO        | NO        |
extranote        | √   |   √         | √       | √         | √               | √    | √        | √          | √       | √               | √        | √           | √              | √          | √          | √         | √         | √    | 18 | NO            | NO          | NO        | NO        |
trimonsave       | NO  |   NO        | NO      | √         | NO              | NO   | NO       | NO         | NO      | NO              | NO       | NO          | NO             | NO         | NO         | NO        | √         | NO   |  2 | NO            | NO          | √         | NO        |
––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
defaultoption    | √   |  NO         | √       | NO        | NO              | √    | √        | NO         | √       | NO              | NO       | √           | √              | √          | √          | √         | NO        | √    | 11 | NO            | NO          | √         | NO        |
defaultvalue     | √   |  NO         | √       | √         | √               | √    | √        | NO         | √       | √               | √        | √           | √              | √          | √          | √         | NO        | √    | 15 | NO            | NO          | √         | NO        |
downloadformat   | NO  |  NO         | √       | NO        | NO              | √    | √        | NO         | NO      | √               | NO       | √           | √              | √          | √          | √         | NO        | √    | 10 | NO            | NO          | √         | NO        |
noanswerdefault  | NO  |  NO         | NO      | NO        | √               | NO   | NO       | NO         | NO      | √               | NO       | NO          | NO             | NO         | NO         | NO        | NO        | NO   |  2 | NO            | NO          | √         | NO        |
lowerbound       | √   |  NO         | NO      | NO        | NO              | √    | √        | NO         | √       | NO              | √        | NO          | NO             | √          | NO         | √         | NO        | √    |  8 | NO            | NO          | √         | NO        |
upperbound       | √   |  NO         | NO      | NO        | NO              | √    | √        | NO         | √       | NO              | √        | NO          | NO             | √          | NO         | √         | NO        | √    |  8 | NO            | NO          | √         | NO        |
options          | NO  |  NO         | NO      | NO        | √               | NO   | NO       | NO         | NO      | √               | NO       | √           | √              | NO         | √          | NO        | NO        | NO   |  5 | NO            | NO          | √         | NO        |
–––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––--–––––––––––––––––––––––––––––––––––––
                       | hiddenfield |  style  | pattern   | labelother      |      | step     | maxfiles   |         | heightinrows    | signed   | labelother  | rates          |            | labelother |           | useeditor | step |    | defaultstatus |             | fullwidth |
                       | element01   |         | minlength | downloadformat  |                 | maxbytes   |         | minimumrequired | decimals | adjustment  | style          |                                     | arearows  |                                         | leftlabel |
                       | element02   |         | maxlength | minimumrequired |                 | filetypes  |         | maximumrequired |                        | differentrates |                                     | areacols  |
                       | element03   |                     | maximumrequired |                                                                                                                                          | minlength |
                       | element04   |                     | adjustment      |                                                                                                                                          | maxlength |
                       | element05   |
```

The three sections of this table are, in the order, for:
- fields that are more or less FOR EACH ITEM
- fields that are specific but very popular among items
- fields that are specific for a single item only (more or less)

Between the first set of columns (referring to fields) and the second set of columns (referring to formats) I added the number of fields having the specific property (specified at the beginning of the row).
As you can see the property "trimonsave" has no title at all to be in the first part of the table. (Only two fields have the property "trimonsave")
This is the reason justifying this PR.

What I would like to reach is described in the following table.
To summarize: I want to drop the trimonsave field from the list of fields common to almost all items and to assign it to ONLY to character and textarea.

```
                   AGE |   AUTOFILL  | BOOLEAN | CHARACTER  | CHECKBOX        | DATE | DATETIME | FILEUPLOAD | INTEGER | MULTISELECT     | NUMERIC  | RADIOBUTTON | RATE           | RECURRENCE | SELECT     | SHORTDATE | TEXTAREA   | TIME |    | FIELDSET      | FIELDSETEND | LABEL     | PAGEBREAK |
content          | √   |   √         | √       | √          | √               | √    | √        | √          | √       | √               | √        | √           | √              | √          | √          | √         | √          | √    | 18 | √             | NO          | √         | NO        |
contentformat    | √   |   √         | √       | √          | √               | √    | √        | √          | √       | √               | √        | √           | √              | √          | √          | √         | √          | √    | 18 | NO            | NO          | √         | NO        |
 
required         | √   |   NO        | √       | √          | √               | √    | √        | √          | √       | √               | √        | √           | √              | √          | √          | √         | √          | √    | 17 | NO            | NO          | NO        | NO        |
indent           | √   |   √         | √       | √          | √               | √    | √        | √          | √       | √               | √        | √           | √              | √          | √          | √         | √          | √    | 18 | NO            | NO          | √         | NO        |
position         | √   |   √         | √       | √          | √               | √    | √        | √          | √       | √               | √        | √           | √              | √          | √          | √         | √          | √    | 18 | NO            | NO          | NO        | NO        |
customnumber     | √   |   √         | √       | √          | √               | √    | √        | √          | √       | √               | √        | √           | √              | √          | √          | √         | √          | √    | 18 | NO            | NO          | √         | NO        |
hideinstructions | √   |   NO        | NO      | √          | √               | √    | √        | NO         | √       | √               | √        | NO          | √              | √          | NO         | √         | √          | √    | 13 | NO            | NO          | NO        | NO        |
variable         | √   |   √         | √       | √          | √               | √    | √        | √          | √       | √               | √        | √           | √              | √          | √          | √         | √          | √    | 18 | NO            | NO          | NO        | NO        |
extranote        | √   |   √         | √       | √          | √               | √    | √        | √          | √       | √               | √        | √           | √              | √          | √          | √         | √          | √    | 18 | NO            | NO          | NO        | NO        |
–––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
defaultoption    | √   |  NO         | √       | NO         | NO              | √    | √        | NO         | √       | NO              | NO       | √           | √              | √          | √          | √         | NO         | √    | 11 | NO            | NO          | √         | NO        |
defaultvalue     | √   |  NO         | √       | √          | √               | √    | √        | NO         | √       | √               | √        | √           | √              | √          | √          | √         | NO         | √    | 15 | NO            | NO          | √         | NO        |
downloadformat   | NO  |  NO         | √       | NO         | NO              | √    | √        | NO         | NO      | √               | NO       | √           | √              | √          | √          | √         | NO         | √    | 10 | NO            | NO          | √         | NO        |
noanswerdefault  | NO  |  NO         | NO      | NO         | √               | NO   | NO       | NO         | NO      | √               | NO       | NO          | NO             | NO         | NO         | NO        | NO         | NO   |  2 | NO            | NO          | √         | NO        |
lowerbound       | √   |  NO         | NO      | NO         | NO              | √    | √        | NO         | √       | NO              | √        | NO          | NO             | √          | NO         | √         | NO         | √    |  8 | NO            | NO          | √         | NO        |
upperbound       | √   |  NO         | NO      | NO         | NO              | √    | √        | NO         | √       | NO              | √        | NO          | NO             | √          | NO         | √         | NO         | √    |  8 | NO            | NO          | √         | NO        |
options          | NO  |  NO         | NO      | NO         | √               | NO   | NO       | NO         | NO      | √               | NO       | √           | √              | NO         | √          | NO        | NO         | NO   |  5 | NO            | NO          | √         | NO        |
–––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––--––––––––––––––––––––––––––––––––––––––––
                       | hiddenfield |  style  | pattern    | labelother      |      | step     | maxfiles   |         | heightinrows    | signed   | labelother  | rates          |            | labelother |           | useeditor  | step |    | defaultstatus |             | fullwidth |
                       | element01   |         | minlength  | downloadformat  |                 | maxbytes   |         | minimumrequired | decimals | adjustment  | style          |                                     | arearows   |                                         | leftlabel |
                       | element02   |         | maxlength  | minimumrequired |                 | filetypes  |         | maximumrequired |                        | differentrates |                                     | areacols   |
                       | element03   |         | trimonsave | maximumrequired |                                                                                                                                          | minlength  |
                       | element04   |                      | adjustment      |                                                                                                                                          | maxlength  |
                       | element05   |                                                                                                                                                                                   | trimonsave |
```

### CODE REVIEW

**Comment by stronk7** [comment]
Maybe you need to rebase this PR? It's showing 4 commits, when 3 have been already merged, they shouldn't be here.

**Comment by stronk7** [comment]
I've a question here:

How will this affect to existing templates (or backups) having the `trimonsave` as part of the "common" fields?

With other words, do you need to add something on restore and template loading for whenever an old configuration arrives as part of the common fields, in order to apply it to the new place within those 2 fields (character and textarea) ?

**Comment by kordan** [comment]
No, at the moment there is no need to change templates and backup.
With this PR I only removed the definition of the property trimonsave from itembase and I added it to specific properties of character and textarea.
Trimonsave was saved into surveyprofield_character and surveyprofield_textarea tables and it is still saved into the same tables.
The difference introduced by this PR is this: 
- before this PR trimonsave property was defined in the itembase class and proposed to each specific item class. Each item class, with the exception of character and textarea, was neglecting the property. Character and textarea were using the property and saving it in their specific table (surveyprofield_character and surveyprofield_textarea).
- after this PR trimonsave property is no longer defined in the itembase class but only locally in character and textarea class (field/(character|textarea)/classes/item). All the other items are not offered to use this property. The property borns in the frame of the two field elements and is managed as local property and saved were it was already saved before.

I hope I well understood your question and I hope I provided a satisfactory answer to it. Do not hesitate to ask more.

**Comment by stronk7** [comment]
Thanks for the confirmation and explanations, all clear now!

**Pull request merged**
