### PR TITLE
CONTRIB-6543 mod_surveypro: code cleanup in relation table

### PR DESCRIPTION
**Pull request by kordan**
very simple PR

### CODE REVIEW

**Comment by stronk7** [comment]
How is this correct? flexible_table specs for the function are:

````
function sortable($bool, $defaultcolumn = NULL, $defaultorder = SORT_ASC) {
````

Why are you moving to hardcoded ASC/DESC in the column?

Sure I'm missing something, but this seems to be a wrong change. Also the issue does not provide any information justifying the change.

Ciao :-)

**Comment by kordan** [comment]
You are right. 
I must provide some information before.
I a cranched surveypro, when I go to the "Branching validation" page, I find the table sorted by sortindex DESC.
If I select the link "Reset table preferences" at the top right corner, nothing changes! I want it ordered, by default, per sortindex ASC. Why it doesn't work?

**Comment by kordan** [comment]
And even now that I quite restored old code, why do I get the little triangle close to sortindex table header?

**Comment by kordan** [comment]
it works fine now even if I don't understand few not relevant details! :(

**Comment by stronk7** [comment]
Merged, thanks!

**Pull request merged**
