### PR TITLE
Polish vowels

### PR DESCRIPTION
**Pull request by kordan**
Please cherry-pick this to (m401|m402|m403) too.

### CODE REVIEW

**Comment by stronk7** [comment]
Maybe you've to rebase this, because it shows 2 commits and it should be only one.

**Comment by kordan** [comment]
Sure. You are right.
Done.

**Comment by stronk7** [comment]
Merged, and cherry-picked to 401, 402 and 403.

**Comment by kordan** [comment]
Yuppi! Thanks.

**Pull request merged**
