### PR TITLE
Removed other string concatenation (m403)

### PR DESCRIPTION
**Pull request by kordan**
This specific PR for MOODLE_403_STABLE because I am going to increase the surveypro version to cache new strings

### CODE REVIEW

**Comment by stronk7** [comment]
And... shouldn't master also get the changes? I mean, we have changed the strings in 401, 402 and 403 (3 separate PRs), but master still has the old, unchanged, strings, isn't it?

**Comment by kordan** [comment]
mmmhhh not sure I got your suggestion.
Didn't you merge lang improvement in  #889?

**Comment by stronk7** [comment]
Yes, and #889 was cherry picked to 401, 402 and 403.

But here, you're providing more lang changes, only for 403, in #892 for 402 and in #891 for 401.

And my question is... what happens with these lang changes and master?

**Comment by kordan** [comment]
You are right.
Executing:
diff -ur --exclude='.git' /Applications/MAMP/htdocs/m402/mod/surveypro /Applications/MAMP/htdocs/m403/mod/surveypro
(where the semantic of trivial)
I get:
--- /Applications/MAMP/htdocs/m402/mod/surveypro/version.php	2023-12-14 19:01:35
+++ /Applications/MAMP/htdocs/m403/mod/surveypro/version.php	2023-12-14 19:00:33
@@ -26,6 +26,6 @@
 
 $plugin->component = 'mod_surveypro';
 $plugin->maturity = MATURITY_BETA;
-$plugin->version = 2023120104;
-$plugin->release = '4.3.2';
+$plugin->version = 2023120102;
+$plugin->release = '4.4dev';
 $plugin->requires = 2023100900;

I will immediately create a PR to increase the version for master only. THANKS!

**Comment by kordan** [comment]
#896

**Pull request merged**
