### PR TITLE
Assigned a class to each landing page

### PR DESCRIPTION
**Pull request by kordan**
In the frame of this PR I also tried to provide a better name to managers. The rationale of this PR is to assign to each section of each area of surveypro a specific class. Once each section will use its specific class it will be simple to:
- better debug the code;
- make code improvements;
- create unit tests.

As far as I know, this PR along with #932 and #931, accomplishes this goal.

What was in my mind (and I hope I reached this target) was to assign a specific class to each landing page of sPro. In other words...
sPro is divided into 6 areas and each area is divided into sections. The structure of sPro, is:

```
[Spro area] surveypro (managed in view.php)
- [section] cover
- [section] submissionslist
- [section] submissionform
- [section] searchsubmissions
[Spro area] layout (managed in layout.php)
- [section] itemslist
- [section] itemsetup
- [section] branchingvalidation
- [section] preview
[Spro area] reports (managed in reports.php)
- [report] attachement overview
- [report] frequency distribution
- [report] late users
- [report] responses per user
- [report] users per count of responses
[Spro area] tools (managed in tools.php)
- [section] export
- [section] import
[Spro area] user templates (managed in utemplates.php)
- [section] manage
- [section] save
- [section] import
- [section] apply
[Spro area] master templates (managed in mtemplates.php)
- [section] save
- [section] apply
```
Well, if I am not wrong, now each section uses a specific class. (reports are an exception)

Names of classes always start with the name of the area and ends with the name of the section. They are:

```
[Spro area] surveypro (managed in view.php)
- [section] cover -----------------------------------> view_cover
- [section] submissionslist -------------------------> view_submissionlist
- [section] submissionform --------------------------> view_submissionform
- [section] searchsubmissions -----------------------> view_submissionsearch
[Spro area] layout (managed in layout.php)
- [section] itemslist -------------------------------> layout_itemlist
- [section] itemsetup -------------------------------> layout_itemsetup
- [section] branchingvalidation ---------------------> layout_branchingvalidation
- [section] preview ---------------------------------> layout_preview
[Spro area] reports (managed in reports.php)
- [report] attachement overview ---------------------> report from its own specific plugin classes
- [report] frequency distribution -------------------> report from its own specific plugin classes
- [report] late users -------------------------------> report from its own specific plugin classes
- [report] responses per user -----------------------> report from its own specific plugin classes
- [report] users per count of responses -------------> report from its own specific plugin classes
[Spro area] tools (managed in tools.php)
- [section] export -----------------------------------> tools_export
- [section] import -----------------------------------> tools_import
[Spro area] user templates (managed in utemplates.php)
- [section] manage -----------------------------------> utemplate_manage
- [section] save -------------------------------------> utemplate_save
- [section] import -----------------------------------> utemplate_import
- [section] apply ------------------------------------> utemplate_apply
[Spro area] master templates (managed in mtemplates.php)
- [section] save -------------------------------------> mtemplate_save
- [section] apply ------------------------------------> mtemplate_apply
```
The corresponding manager (still, if I am not wrong) is named with the name of the section and finishes with 'man'. So, for instance: corverman, itemlistman, exportman, manageman and so forth.

### CODE REVIEW

**Comment by stronk7** [comment]
Uh, ok. this is conflicting now...

**Comment by stronk7** [comment]
PS: I've done the push to GitHub (origin) already, you don't need to do it. Instead, ensure that your local/all_classes is the same I've sent to origin by doing:

```
git fetch --all --prune
git co all_classes
git reset --hard origin/all_classes
```

And done, now both your local and github all_classes branches will have the very same commits.

Ciao :-)

**Comment by kordan** [comment]
How can I be sure that by push --force I am not deleting some important change I did on github?
My copy is FOR SURE different from the one on github but I have no evidence of the difference.
I even know github has 5 commit more than my copy. So my question is: am I going to make a mess?
This is the usual step freezing me.

**Comment by stronk7** [comment]
Well, you can check what's different. Just do:

```
git co all_classes
git diff origin/all_classes
```
 
 to see which changes, since last time you pushed that branch, have happened.
 
 Or, also, you can make:
 
 ```
git co all_classes
git show HEAD
```

to see how your top local commit in the branch is looking.

Once you're 100% sure that what is ready to be pushed is correct, just do it.

Ciao :-)

**Comment by stronk7** [comment]
BTW, question, this one is for master only, correct?

**Comment by kordan** [comment]
Yes, sure. Master only.

**Comment by stronk7** [comment]
Buff, this was huge! As far as everything is passing and I've not seen anything strange to report... merged!

**Comment by kordan** [comment]
SUPERRRRRR. PR list is empty and this, finally, open to unit test!
THANK YOU!

**Pull request merged**
