### PR TITLE
Fixing invalid query missing option from the group by

### PR DESCRIPTION
**Pull request by donkeyx**
Hey guys, 

Not sure of the workflow but I have found an invalid query missing one of the options in the group by. I have just committed to the 27 branch but it is also invalid on master? Happy for feedback? Also, not 100% sure what the intention was for that query so might need checking. 

Cheers Dave.

### CODE REVIEW

**Comment by donkeyx** [comment]
Just fixed another bug that was breaking scales.

**Comment by kordan** [comment]
Ciao Dave
and thanks for using, testing and reporting issues for this module.
As far as I understand, you had a surveypro with some field and you tried to overwrite it with a user or master template.
At overwrite time you selected the "Delete all elements" radio button (if overwriting with usertemplate).
Is this true?
I did exactly this process but I didn't get any error.
Can you please give me some more details in order to allow me to reproduce the issue?
Thanks in advance.

**Comment by donkeyx** [comment]
Hey kordan, 

You are right that the scales are not in the survey pro but the code introduced messes with all moodle scales. So basically when you have that code uncommented and you attempt to edit a scale, you will get this message: 

upload_png_694x411_pixels

Sorry, I should have included that originally ;).

**Comment by donkeyx** [comment]
Hey Kordon, 

I have just added another couple of changes which basically save the survey state if you press pause/next/previous. Before if you had half filled the current page you were on, and pressed one of these buttons, you would loose the partial data from that form. Now it will save the state of the form no matter what action you take. 

The main reason was to allow pausing and not loosing you data if there was just a single page and you had half filled it out. But it will also allow for the next and previous to do the same thing as well. 

Cheers Dave.

**Comment by kordan** [comment]
ok Dave
your solution for the 'Field "grade" does not exist in table "surveypro"' is now part of the main distribution in each branch.
About the second issue: "to save the survey state if you press pause/next/previous", I merged your solution into my local code. I have to remember why I commented the solution of your proposal because if was already part of the main code. I hope to push it to github as soon as I remember how the history is.
Thanks for your involvement.

**Comment by donkeyx** [comment]
Coolies, thanks kordan and let me know if you need any testing etc. happy
to help

**Comment by kordan** [comment]
yes Dave,
I remember the story now.

Let's say you have a surveypro with 10 pages.
You are filling page 4 and you have a doubt about what you entered in page 3.
So you press the "Previous" button.
What I suppose is that you want to see page 3 without any boring and useless question
but maybe in page 4 there is a mandatory field that forces you to fill it before redirecting you back to page 3.

This is an undesired behaviour that can not be allowed!
To let you return to page 3 without any question, the code has to jump the form validation but this means it can not be allowed to save the form.

The same is true if the user pushes the "pause" button. User has to go. He/she no longer care the surveypro. He/she want to go and doesn't want any boring and useless question...

This is why I have
if (!$prevbutton && !$pausebutton) {
about line 120 of view_userform.php

---

Second modification: about line 690 of view_userform.class.php the management of "pause" and "prev" buttons is useless.
This is the comment I added just by the code:

// submit buttons are 3 and only 3 (And not 5 as it may appear!)
// if empty($this->formdata->submissionid) this means that:
// 1) you pressed the "save as new" button
// 2) the submission is unknown to the db
//
// case 1) for sure the "pause" button or "prev" button were not pressed, so they don't need any management
// case 2) the form is in its first page so:
//         a) "prev" button does not exist
//         b) the "pause" button, even whether pressed, does not lead to save because...
//            (if the user presses "pause" this means he/she want to leave
//            and he/she doesn't want any break of balls with undesired questions)
//            Because of this, if "pause" was requested I am not here infact
//            in view_userform.php the save_user_data() method is jumped
//
// so, the overall behaviour is: do not manage these two buttons. This management is useless.
// if ($nextbutton || $pausebutton || $prevbutton) {

Tel me if you can imagine any better solution!

**Comment by donkeyx** [comment]
Hey Kordan,

I am thinking that the pause button it better placed to save the current
state and pause the survey, rather than just redirecting which is what it
does now. That functionality would be better in a cancel/exit style
button.  Same goes for forward/backward: if you were part way through
filling out a large page, then wanted to look at the last previous page,
you progress would be lost without the changes. The pause button is also
shown even if there is no pagination, for the case where someone had a huge
single page survey with heaps of questions. I am thinking from the cases in
sites like "survey monkey", which pretty much saves you state whichever
direction/button you press, which allows you to go back/forward without
loosing progress. I am thinking these cases would make up the majority and
if people really wanted to cancel they would just close the page or click a
bookmark i suspect?

**Comment by kordan** [comment]
About the save process... a good solution has to be found.
Possible solutions:
- save dirty records (with values not validated)
- add a new "cancel/exit" button
- something in the middle like "save only valid values" without questioning

**Comment by donkeyx** [comment]
Sounds like a plan ;). You pretty much want to be able to move around the
survey back/forward/pause to make it really nice, without loosing any
entries. And that would work perfectly if you just discard anything that is
invalid. We are using the current changes in prod now without any trouble
and seems to be working ok. Another alternative is to stop them leaving the
page until the have valid data but either will work.

**Comment by kordan** [comment]
ok, try it, if you like.
Now data is saved on "back" and "pause" too.
If you test it, let me know how does it go, please.
Next Tuesday I will finish the work.
I only pushed to master, not to any other branch.

**Comment by kordan** [comment]
I just completed the save process for each pressed button.
During my tests I didn't find any issue. If you like, test the last master release on a test server.
I updated only the master branch of surveypro.

**Pull request closed without merging**
