### PR TITLE
fixed an issue left from PR 415

### PR DESCRIPTION
**Pull request by kordan**

### CODE REVIEW

**Comment by stronk7** [comment]
I'm confused... didn't we exactly applied this change in #415 ? When did us reverted it? Looking...

**Comment by stronk7** [comment]
Yeah, code is already there... what am I missing?

https://github.com/kordan/moodle-mod_surveypro/blob/master/classes/itembase.php#L895

**Comment by kordan** [comment]
You are right but yesterday when I went to import a usertemplate I found I had not it.
Maybe I had not git fetch git pull but it is strange.
Actually, at the moment if I git co master I see the right code. I am missing something too.

**Comment by stronk7** [comment]
(y). I imagine some pull was missing your side or something like that. I tried to merge it here (after pulling) and it ended with zero-lines merged (meaning, everything was there already).

So well closed! Let's forget it. 👍

**Pull request closed without merging**
