### PR TITLE
Update strings for es-mx language

### PR DESCRIPTION
**Pull request by germanvaleroelizondo**
Hi,
I have been very busy teaching undergraduate students. I had some free time and updated the es-mx language strings.

### CODE REVIEW

**Comment by kordan** [comment]
Cool, German! Thank you.
I stopped the development of surveypro because it was no longer needed by my office. Even this I think it still works fine. I was moved to different jobs but as soon as surveypro will became useful once again I will be asked to move back to it.
I am going to integrate your file as soon as possible.
Super super thank you!

**Comment by germanvaleroelizondo** [comment]
Thank you for the continuing improvements of this plugin. 

Maybe you could submit it to the Moodle plugins database, so that it would be easier for Moodlers to install it in their servers.

As soon as I finish the project I am currently working on, I will test the new version and comment about it.

**Comment by kordan** [comment]
I don't want to upload this module to plugins database because it doesn't include unit tests. (Alias: I feel this is not a good enough plugin)
In addition, I am no longer developing surveypro (at the moment) so I would not find the needed time to fix issues discovered by users.

**Comment by kordan** [comment]
I asked to moodle HQ to include surveypro in moodle in order to have it always apdate but they refused it.

**Comment by germanvaleroelizondo** [comment]
Please, reconsider.
It is not strictly necessary to have unit testsin your plugin.
Your plugin IS GOOD enough. There are 11 forks of it already.
I really think it would be very useful for many Moodlers (such as myself and my school teachers).

**Comment by kordan** [comment]
Dear German,
surveypro is a piece of my hearth.
I really would like to have the time and to get the knowledge to maintain and improve it but my professional time is conditioned by my boss and my personal time is alreday heavly divided between private issues. I am in front to a fork. I should start by finding the time to study unit tests, to get in details for the module refused by moodle in the cell phone, to fix issues for some user item not 100% correctly written in moodle, and even more. There is no way for me to do this all by myself even because I am quite old and my progresses take a long time. I am open to get help from wherever but, with only one exception by a special moodle person, I am alone. This is why I believe that in the absence of a twist I will progressively abandone the module.

**Pull request merged**
