### PR TITLE
CONTRIB-6252 mod_surveypro: required 2 library

### PR DESCRIPTION
**Pull request by kordan**
I found that with the merge of c5b98c3
behat test were no longer working fine.
I made a
git co c5b98c3
git diff 23d88bd > local_file_on_my_desktop.txt
and I found that two library were no longer called.

This PR to add them ance again.
NOT SURE AT ALL THIS IS A GOOD PRACTICE.

### CODE REVIEW

**Comment by stronk7** [comment]
Uhm... I'm not sure I understand why generator should require/include those files at all. I can imagine it using lib.php stuff, but locallib and behat lib?

Looking to see which the dependency is, because maybe it must be fixed another way...

**Comment by stronk7** [comment]
Aha, I see... you created get_dummy_contents() as a shortcut to have item own generators and you use it in behat for quickly creating items.

So, really... is that file (tests/behat/behat_mod_surveypro.php) the one that should include tests/behat/lib_behattest.php (and locallib.php because it uses functions there).

Also, I think tests/behat/lib_behattest.php should include lib.php because it uses constants from there.

Of course... doing this correctly should imply having proper generators for all items and using them instead of that dummy function, but that's another story (complex/long one right now).

So.. I think the solution to this should be something like:

1) keep generator as is, not adding the includes there. Nothing is missing (note that in the future, if me make it more complete... sure some stuff will be required, but it's not for now).

2) make tests/behat/behat_mod_surveypro.php to include the stuff it uses (tests/behat/lib_behattest.php and locallib.php).

3) make tests/behat/lib_behattest.php to include the stuff it uses (lib.php).

Preparing here a commit to see if everything works that way...

**Comment by stronk7** [comment]
I see, it's problematic because only generators should be used to create stuff... instead of behat stuff... uhm... maybe it requires a small (not definitive) reorganization... will try later if I've time.

**Comment by stronk7** [comment]
Bah,

I'm afraid, no time now. If someday we make the generator to evolve and get the baton over that dummy function... then will be time to do / clean them. Maybe it would not be crazy to create an issue about that (move from dummy to proper generator). To avoid forgetting.

**Comment by stronk7** [comment]
Merged, thanks!

**Comment by kordan** [comment]
Thanks for your time! \o/

**Pull request merged**
