### PR TITLE
Improved reports breadcrumb

### PR DESCRIPTION
**Pull request by kordan**
Trying to understand the missing or duplicated item in the tools breadcrumb I found inconsistency in breadcrumb here and there. At the moment the duplicated breadcrumb item is winning against me.

This PR should be cherry-picked to MOODLE_401|402|403_STABLE too.

### CODE REVIEW

**Comment by stronk7** [comment]
It seems that we have some good conflicts here...

**Comment by kordan** [comment]
ok, ok
let me solve it

**Comment by kordan** [comment]
pushed again

**Comment by kordan** [comment]
## OBSERVATIONS ##

# Intro #
To explain the issue I refer to the enhancement_reports_breadcrumb branch of surveypro, in github, installed on last moodle 4.3 stable. At first, I inhibit what I do with $PAGE->navbar->add in my branch to reload it later.

# Shortly and unambiguously #
```
cd /path/to/your/moodle_folder/mod/surveypro
[master|✔] git co master
[master ↓12] git fetch origin --prune
[master|✔] git pull
[master|✔] git br enhancement_reports_breadcrumb origin/enhancement_reports_breadcrumb
[master|✔] git co enhancement_reports_breadcrumb
[enhancement_reports_breadcrumb|✔] git grep -rl '$PAGE->navbar->add' . | xargs gsed -i 's/$PAGE->navbar->add/\/\/ $PAGE->navbar->add/g'
[enhancement_reports_breadcrumb|✚13] gsed -i 's/\/\/ $PAGE->navbar->add/$PAGE->navbar->add/g' ./index.php
[enhancement_reports_breadcrumb|✚12]
```

If you do not use gsed use awk or whatever you prefer. The idea, as you already 100% understood, is: replace each instance of '$PAGE->navbar->add' with '// $PAGE->navbar->add'. The one in ./index.php is 100% not relevant. Its replacement does not matter.

You should have 13-1 files changed.

# Context of the problem #
The structure of surveypro (in my mind) is:

```
[Spro instance] Surveypro
    • [Spro area] surveypro (managed in view.php)
        - [Spro section] cover
        - [Spro section] submissionslist
        - [Spro section] submissionform
        - [Spro section] searchsubmissions
    • [Spro area] layout (managed in layout.php)
        - [Spro section] itemslist
        - [Spro section] itemsetup
        - [Spro section] branchingvalidation
        - [Spro section] preview
    • [Spro area] reports (managed in reports.php)
        No sections here. reports.php delegates execution to specific report
    • [Spro area] tools (managed in tools.php)
        - [Spro section] export
        - [Spro section] import
    • [Spro area] user templates (managed in utemplates.php)
        - [Spro section] manage
        - [Spro section] save
        - [Spro section] import
        - [Spro section] apply
    • [Spro area] master templates (managed in mtemplates.php)
        - [Spro section] save
        - [Spro section] apply
```

# CHAPTER 1 #
Switch to theme classic.
Go to an instance of surveypro. If you already have it in your local moodle testing site, it is fine. Only verify you have, at least, one non hidden field in your surveypro. Add the Navigation block to each page of surveypro. Turn off the Blocks editing and look at the page.
I am confident you are in front of:
http://localhost:8888/m403/mod/surveypro/view.php?id=xxx

The breadcrumb in this page is:
    [Site home] / Courses / [Course name] / [Course section] / [Spro instance]
In my case:
    Home / Courses / SPC / General / wip4
(SPC: SurveyPro Course, wip4: 4th release of a work in progress)

Somewhere, in the Navigation block you should have:

```
wip4
[] Surveypro
[] Layout
[] Reports
[] Tools
[] User templates
[] Master templates
```

where each area name is prefixed by a small blue square (using the theme classic)

-> Now click on "[] Surveypro"
The expected breadcrumb is:
```
    [Site home] / [Courses] / [Course name] / [Course section] / [Spro instance] / [Spro area] / [Spro section]
```
but what I get is:
```
    [Site home] / [Courses] / [Course name] / [Course section] / [Spro instance] ONLY.
```
[Spro area] and [Spro section] are missing. Ok, I may agree. I should personally take care of the last two breadcrumb elements.

-> Now click on "[] Layout"
The expected breadcrumb is the same it was expected before
but what is returned is:
```
    [Site home] / [Courses] / [Course name] / [Course section] / [Spro instance] / [Spro area] / [Spro area].
```
[Spro area] is added and displayed twice while [Spro section], as expected, is missing.

Given the expected breadcrumb is ALWAYS the same:
```
[Site home] / [Courses] / [Course name] / [Course section] / [Spro instance] / [Spro area] / [Spro section]
```
in the next table I show, for each link in the Navigation block, the breadcrumb actually displayed in the landing page (without first 4 common elements).

```
        link        |                     breadcrumb
[] Surveypro        | ... [Spro instance]
[] Layout           | ... [Spro instance] / [Spro area] / [Spro area]
[] Reports          | ... [Spro instance]
[] Tools            | ... [Spro instance] / [Spro area] / [Spro area]
[] User templates   | ... [Spro instance]
[] Master templates | ... [Spro instance] / [Spro area] / [Spro area]
```

# Curious note #
It is curious that the two different behaviors are well divided between odd and even links.
The 1st behaves like the 3rd and the 5th while the 2nd behaves like the 4th and the 6th.

# Sad note #
Whatever link I select from the Navigation block, it NEVER becomes bold as it should. (A suggestion to fix this problem is in https://moodledev.io/docs/apis/core/navigation#q-my-page-is-on-the-navigation-but-it-doesnt-find-it but now there is something more relevant to fix). Anyway, the issue seems deeper than the one described in the moodledev page because I have only ONE link per each area in the Navigation block but MANY links (one per sections) per each area that should make bold the item in the Navigation block.
I do not want to change the url in the Navigation block from:
```
$paramurl = ['s' => $cm->instance]
```
to
```
$paramurl = ['s' => $cm->instance, 'section' => 'something']
```
otherwise I will miss for ever the hope to see the link in bold.
And, furthermore:
How can I assign more than one:
```
navigation_node::override_active_url(
    new moodle_url('/your/url/here.php', [
        'param' => 'value',
    ])
);
```
to my link in the navigation block? But this, as said, is something it will arrive later.

# Details: the first #
Links in the Navigation block are all built giving them the same format. They are defined in the function surveypro_get_link_visibility_condition in lib.php and they are:
```
    $paramurl = ['s' => $cm->instance];
    $url = new \moodle_url('/mod/surveypro/'.$landing_page.'.php', $paramurl);
```
where landing_page is one of ['view', 'layout', 'reports', 'tools', 'utemplates', 'mtemplates']

# Details: the second #
The accepting code in each landing page is ALWAYS the same.
It is, mutatis mutandis, (it is a sentence from latin and I am quite sure you know it but, in any case, it means: changing what needs to be changed)
```
    require_once(dirname(__FILE__).'/../../config.php');

    $id = optional_param('id', 0, PARAM_INT); // Course_module id.
    $s = optional_param('s', 0, PARAM_INT);   // Surveypro instance id.
    $section = optional_param('section', 'save', PARAM_ALPHAEXT); // The section of code to execute.

    // Verify I used correct names all along the module code.
    $validsections = ['save', 'apply'];
    if (!in_array($section, $validsections)) {
        $message = 'The section param \''.$section.'\' is invalid.';
        debugging('Error at line '.__LINE__.' of file '.__FILE__.'. '.$message , DEBUG_DEVELOPER);
    }
    // End of: Verify I used correct names all along the module code.
```

# Details: the third #
Likewise, also the $PAGE construction is the same, mutatis mutandis, in each section of each landing_page.

```
    // Begin of: set $PAGE deatils.
    $url = new \moodle_url('/mod/surveypro/mtemplates.php', ['s' => $surveypro->id, 'section' => 'save']);
    $PAGE->set_url($url);
    $PAGE->set_context($context);
    $PAGE->set_cm($cm);
    $PAGE->set_title($surveypro->name);
    $PAGE->set_heading($course->shortname);
    // $PAGE->navbar->add(get_string('mtemplate', 'mod_surveypro'), $url);
    // $PAGE->navbar->add(get_string('mtemplate_save', 'mod_surveypro'));
    // Is it useful? $PAGE->add_body_class('mediumwidth');.
    // End of: set $PAGE deatils.
```

# Finally the question #
1) why do even if I use the same code in the Navigation block and in each landing_page I get different output in the breadcrumb?

I made a lot more testing resetting the code in the branch or continuing with this amended code but whatever I found is always referable to this first weird behavior. Because of this I omit the other chapters (Chapter 2, 3, 4 and 5) of my observation.

# Things from other worlds: first experience #
If you want to see really strange behaviur, do this:
```
git reset --hard
```
return to your local moodle testing site in the browser always in classic, select each area link from the Navigation block and in each surveypro area landing page jump between surveypro sections using the jump menu. You will see incredible breadcrumbs like:
```
... / wip4 / Layout / Layout / Layout / Elements
```
if you arrive to Elements section from the Navigation block
but:
```
... / wip4 / Layout / Elements
```
if you jump, from Elements to Preview, using the jump menu and return back to Elements still using the jump menu.

Of course I know that in the Navigation block I use links like
```
    $paramurl = ['s' => $cm->instance];
    $url = new \moodle_url('/mod/surveypro/'.$landing_page.'.php', $paramurl);
```
while in the jump menu I use different links like
```
    $paramurl = ['s' => $cm->instance, 'section' => 'something'];
    $url = new \moodle_url('/mod/surveypro/'.$landing_page.'.php', $paramurl);
```
but I can not imagine any other solution.

I did also made some more tests and I arrived, once again, to mad solutions.
I can not see a way to get those three elements:

1. the breadcrumb when arriving from the Navigation block;
2. the breadcrumb when arriving from the jump menu;
3. the bold selection of the text in the Navigation block FOR EACH section of the area;
working fine at the same time.

# Things from other worlds: second experience #
If you want to still see things of the other world, do this:
```
cd /path/to/your/moodle_folder/mod/surveypro
cp tools.php foobar.php
edit lib.php and change line 915 from
$url = new \moodle_url('/mod/surveypro/tools.php', $paramurl);
to
$url = new \moodle_url('/mod/surveypro/foobar.php', $paramurl);
```

Return to the browser.
Write in the address bar: http://localhost:8888/m403/mod/surveypro/foobar.php?id=xxx
The breadcrumb is correct.
Go to your modle test site and select the link tool in the Navigation block.
The breadcrumb is NOT correct.

It is time to stop. Do you agree?

**Comment by kordan** [comment]
Jeaaaaa.
It is not ONLY my fault.
https://tracker.moodle.org/browse/MDL-80602

**Pull request closed without merging**
