### PR TITLE
NOBUG mod_surveypro: rewritten missing line

### PR DESCRIPTION
**Pull request by kordan**
GRRRR It may happen!!

### CODE REVIEW

**Comment by kordan** [comment]
automergin as 200% safe

**Comment by stronk7** [comment]
Sometimes.. it happens, LOL, well done!

**Comment by stronk7** [comment]
(I'm afraid I did not detect it in the middle of all those repeating changes, grrr)

**Comment by kordan** [comment]
NP my friend. All seems fine now with my ET. Thanks for all you commitment. 👍

**Pull request merged**
