### PR TITLE
introduced pluginusesdbtable property

### PR DESCRIPTION
**Pull request by kordan**
Reduced the number of call to $DB->get_manager()->table_exists() introducing the item propery pluginusesdbtable

### CODE REVIEW

**Comment by kordan** [comment]
100% behat test passed

**Comment by stronk7** [comment]
Uhm... good approach... just may be... it would be better to:

1) don't use the property at all.
2) implement the function ````get_pluginusesdbtable()```` in the base element, returning the most usual value (true?).
3) the types being false will override the function, returning false.

Thoughts?

**Comment by kordan** [comment]
I replaced this PR with #534. I don't know why but this PR is different from the one I supposed it was.

**Comment by stronk7** [comment]
So, with #534 replacing this... this can be closed, yes?

**Pull request closed without merging**
