### PR TITLE
NOBUG mod_surveypro: specified the pass by ref parameter

### PR DESCRIPTION
**Pull request by kordan**
I only changed
public function userform_save_preprocessing($answer, $olduseranswer, $searchform) {
to
public function userform_save_preprocessing($answer, &$olduseranswer, $searchform) {
to better see that I am passing $olduseranswer by ref and better understand why I only change $olduseranswer->content returning nothing.

### CODE REVIEW

**Comment by stronk7** [comment]
Are you sure this is needed? If the parameter passed if an object, then it's already passed by ref. Only arrays may need this.

**Comment by stronk7** [comment]
(also, there are conflicts to solve here, it seems)

**Comment by kordan** [comment]
> Are you sure this is needed? If the parameter passed if an object, then it's already passed by ref. Only arrays may need this.

Yes, I am sure it is not necessary at all but I think it is not an error.
I added it only to better see that I am passing $olduseranswer by ref and better understand why I only change $olduseranswer->content returning nothing.

**Comment by stronk7** [comment]
(as you wish, although I'm not fully convinced)

Merged!

**Pull request merged**
