### PR TITLE
CONTRIB-6417 mod_surveypro: changed get_submission query

### PR DESCRIPTION
**Pull request by kordan**
the original reason for this issue is that the admin was alowed to submit a response but was not allowed to "see" it among responses until he was enrolled in the
course
but
I also found that character elemnts should also be searched for substring and this was still not allowed.

### CODE REVIEW

**Comment by kordan** [comment]
waiting for travis-ci response

**Comment by stronk7** [comment]
Sorry Daniele, I've been trying to understand what's all this $searchquery and don't get it. It is to look for submissions having some content? How can I see it in action?

Also, note that, while trying to get $searchquery to work... I detected #154 and also another database failure using the "Submitting users" report:

````
Coding error detected, it must be fixed by a programmer: User id is required when printing user avatar image.

line 214 of /lib/outputcomponents.php: coding_exception thrown
line 2488 of /lib/outputrenderers.php: call to user_picture->__construct()
line 128 of /mod/surveypro/report/submitting/classes/report.php: call to core_renderer->user_picture()
line 61 of /mod/surveypro/report/submitting/view.php: call to surveyproreport_submitting_report->fetch_data()
````

So, I'm going to leave this not merged until I get a little bit of information about that $searchquery stuff.

**Comment by stronk7** [comment]
Bah, forget my previous comment related about the searchable thing. I was imagining it was different from the search we were talking the other day and, because of a coincidence, i was using a survey without any searchable fields...

Considering this again... no matter of that... the error above is legit and happened to me.

**Comment by stronk7** [comment]
Merged thanks. Summary of comments (ignore the previous):

- I find a little bit imperfect that, once you've performed the search and the results are shown in the view submissions page... there is not a reference about what is being show. IMO, together with the "Show all responses" button there should be some text showing the current search criteria. Without that, it's really hard to remember what was being searched.
- More yet... maybe, I'd allow that, whenever you go back to the search tab (maybe it shoud be renamed "Filter" instead of "Search") I'd make it to remember the last search criteria, allowing easy modification instead of having to build a complete new search. Surely with a button to reset it at any moment.
- Note that the 2 points above are just suggestions, for your consideration. Just sharing them because they called my attention and I'm explained how I'd expect, as a user, to work.
- #154 needs to be applied to fix that report.
- The other error I commented above:
````
Coding error detected, it must be fixed by a programmer: User id is required when printing user avatar image.

line 214 of /lib/outputcomponents.php: coding_exception thrown
line 2488 of /lib/outputrenderers.php: call to user_picture->__construct()
line 128 of /mod/surveypro/report/submitting/classes/report.php: call to core_renderer->user_picture()
line 61 of /mod/surveypro/report/submitting/view.php: call to surveyproreport_submitting_report->fetch_data()
````

Ciao :-)

**Pull request merged**
