### PR TITLE
Require

### PR DESCRIPTION
**Pull request by kordan**
Built on top of #772.
Following suggestion from sonarqube I tried to have homogeneous require at the beginning of the files.

### CODE REVIEW

**Comment by stronk7** [comment]
The only new commit that I can see in this issue is the "[minor changes to satisfy gitlab tests](https://github.com/kordan/moodle-mod_surveypro/pull/773/commits/73aa9a740ad43c03fea7626dfaf910fc1a16356f)" one, that seems to be entirely about adding missing commas and other coding-style issues (mainly).

Is that correct? Just asking because the description of this PR (require moves) is completely different to the code that I've found. Please check and/or clarify the purpose of this PR.

Ciao 🚨

**Comment by kordan** [comment]
Today I reached a good point (tests are once again all passing). Tomorrow I will reply to this question, too.
At the moment I have no idea about the answer.

**Comment by kordan** [comment]
Yes, your comment is correct.

Sonarqube (the software making tests over the code sent to gitlab) was asking me to:
- make require homogeneous;
- add a comma (',') even after the last array element;
- delete unreachable lines of code (for instance, in cases like: return $a; die;);
- change 'and' in '&&'.

In the frame of this silly fix I found some more easy issues like comments not beginning with upper case letter and other even minor details that I fixed. In spite of this, I leaved the PR description related only to the original reason who gave origin to the branch.

So, let's say: yes the branch is really silly and is correct as it is.

**Comment by kordan** [comment]
Sure! (y)

**Pull request merged**
