### PR TITLE
CONTRIB-6278 mod_surveypro: added a flag to include hidden items too

### PR DESCRIPTION
**Pull request by kordan**
This is the first time I touch the power of git.
Checking the code, getting branch id from git logs, I found that the error was introduced a long time ago making "code simpler".
This opens to two different thoughts:
1) the module is actually not used, with the exception of me and Andrea (Can I drop backward compatibility)
2) for the first time I have to say thanks to git.

### CODE REVIEW

**Comment by stronk7** [comment]
Sorry, I'm a bit confused by your comments.

1) Do you mean this is a bug that was introduced by #59 ?
2) What do you mean by drop backward compatibility? Changing the function parameters? Or ?
3) Maybe this behavior should be covered with some test, it's not clear for me what's being achieved here.

Ciao :-)

**Comment by kordan** [comment]
1) I don't remember the PR number but the one you wrote should be correct.
2) I spent csome time to take care to backward compatibility. Was it time wasted?
3) Yes. I agree. I am developing some test exactly for this reason.
What is achieved here is this: when you look at the item list (in the item table in http://localhost/head/mod/surveypro/layout_manage.php?id=xxx) you can see visible and hidden items too. Because of this error, hiding an item in that list (through the "eye" button) was moving the item OUT OF the table.

**Comment by stronk7** [comment]
Merged, thanks!

**Comment by kordan** [comment]
Super thanks!

**Pull request merged**
