### PR TITLE
Added some cron tasks (OLD: still here for security reasons ONLY)

### PR DESCRIPTION
**Pull request by kordan**
Teachers asked for surveypro to send a periodic email to students not filling the survey.
I divided the job in three tasks:
1) mail_neverstartedmod_surveypro\task\mail_neverstarted
Reminder to be sent each monday at 8 in the morning
2) mod_surveypro\task\mail_pauseresume
Reminder to be sent each monday, wednesday and friday at 8 in the morning
3) mod_surveypro\task\mail_oneshotmp
Reminder to be sent each 2 hours

1 is addressed to people who never started to fill the survey
2 is addressed to people that started to fill the survey where the pause/resume option is enabled but left it in the middle
3 is addressed to people filling a multipage survey where the pause/resume option is NOT enabled. It seems that the reminder is a non sense because pause/resume option is NOT enabled so people is supposed to get in, fill and submit. But with surveys spanning multiple pages each time the student goes to a different page, the answers to the elements of the left page are saved to db and the status of the submission is set to "in progress" as if the pause/resume option was actually enabled.

### CODE REVIEW

**Comment by stronk7** [comment]
I imagine we can merge this... just a few comments...

1) it's conflicting now that I've merged the other PRs.

2) In upgrade, you're updating all the surveypro->pauseresume from 1 to 2... the question is... is the 1 value going to be used for something different after the upgrade? It would be great to have a definition of all the values (ideally as constants) somewhere. Not needed for this PR, but it helps to keep code easier to read.

3) Unit tests, unit tests... we need to start adding tests for everything new added. Again, not critical for this PR but it's my mission to remind it to you! ;-)

4) Small detail... it seems that there are a few "MOODLE_INTERNAL" checks that aren't really needed. Files with only one class and without any require/include... we should try to remove all those codechecker warnings towards better code.

Other than that, it looks great.

**Comment by stronk7** [comment]
Looks ok, I imagine you've tested the tasks work as expected. So all we need is to resolve the conflicts and this can be merged.

**Comment by kordan** [comment]
I am preparing a PR with constants.
Once it will be part of the code, I will change:
    if ($oldversion < 2022041400) {
        $newcontent = '2';
        $oldcontent = '1';

        $sql = 'UPDATE {surveypro} SET pauseresume = :newcontent WHERE pauseresume = :oldcontent';
        $DB->execute($sql, array('oldcontent' => $oldcontent, 'newcontent' => $newcontent));

        // Surveypro savepoint reached.
        upgrade_mod_savepoint(true, 2022041400, 'surveypro');
    }

to 

    if ($oldversion < 2022041400) {
        $newcontent = SURVEYPRO_PAUSERESUMENOEMAIL;
        $oldcontent = '1'; // Old Pause/Resume is allowed.

        $sql = 'UPDATE {surveypro} SET pauseresume = :newcontent WHERE pauseresume = :oldcontent';
        $DB->execute($sql, array('oldcontent' => $oldcontent, 'newcontent' => $newcontent));

        // Surveypro savepoint reached.
        upgrade_mod_savepoint(true, 2022041400, 'surveypro');
    }

In the other parts of the code the four constants
        /**
         * KIND OF SUBMISSION
         */
        define('SURVEYPRO_ONESHOTNOEMAIL',     0);
        define('SURVEYPRO_ONESHOTEMAIL',       1);
        define('SURVEYPRO_PAUSERESUMENOEMAIL', 2);
        define('SURVEYPRO_PAUSERESUMEEMAIL',   3);
are already in use.

**Comment by kordan** [comment]
git is always a slippery ground for me.
For instance I found this morning that the field/autofill/tests/behat/preserve_autofillpersonaldata.feature file
that I moved last week in the frame of https://github.com/kordan/moodle-mod_surveypro/pull/661
no longer was part of the code.

I included it once more but git always remains a bit obscure.
Once this PR will be part of the code I will add locally some debugging code and I will test it again for a week.
$CFG->divertallemailsto = '...'; will help me.
If, as I feel, it will be all right, I will delete the debugging code and stop. 
Otherwise I will push fixes.

**Pull request closed without merging**
