### PR TITLE
NOBUG mod_surveypro: changed feature names to unique names

### PR DESCRIPTION
**Pull request by kordan**

### CODE REVIEW

**Comment by stronk7** [comment]
Sounds to me that yesterday I did a quick grep and found some more dupes here and there... looking...

**Comment by kordan** [comment]
the best info I get from this comment is that you know a regex to find for duplicate texts. Who do you do?

**Comment by stronk7** [comment]
These:

- apply a COLLES mastertemplate to test graphs
- apply a mastertemplate
- make a submission test for each available item
- validate feebacks of creation and submit using all the principal combinations of settings

**Comment by kordan** [comment]
Yes, there are a lot
Let me fix them all.
Thanks.

**Comment by stronk7** [comment]
ag --nofilename 'Feature: ' | sort

**Comment by stronk7** [comment]
grep -rh 'Feature: ' | sort

**Comment by stronk7** [comment]
not really sure what you did here. I'm holding this till we can chat about it. That merge commit should not be there.

**Comment by kordan** [comment]
probably the conflict is mainly due to the branch NOBUG_tabsupgrade2 that I always merge before running behat tests

**Comment by kordan** [comment]
Is something blocking the NOBUG_tabsupgrade2 integration?

**Comment by stronk7** [comment]
Ok, I'm going to merge this... although there is something that we must discuss. Please remember it to me the next time we talk. It's about those separate features (1 of 7, 2 of 7...) that you've created. Maybe there is another way to do them, clearer and, surely better because the features should not have numbers like that.

As said, let's discuss about them later. Apart from that, this PR is ok, I think.

**Comment by stronk7** [comment]
Merged, thanks!

**Pull request merged**
